---
- name: Cria VPC 
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
  register: my_vpc

- name: Salva o ID do VPC na Variavel vpc_id
  set_fact:
    vpc_id: "{{ my_vpc.vpc.id }}"

- name: Cria a subnet PUBLICA01
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ public_subnet_1_cidr }}"
    az: "{{ aws_region }}{{ aws_region_az_c }}"
    resource_tags:
      Name: "public-subnet01"
  register: my_public_subnet01

- name: Cria a subnet PUBLICA02
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ public_subnet_2_cidr }}"
    az: "{{ aws_region }}{{ aws_region_az_b }}"
    resource_tags:
      Name: "public-subnet02"
  register: my_public_subnet02

- name: Cria a subnet PRIVADA01
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ private_subnet_1_cidr }}"
    az: "{{ aws_region }}{{ aws_region_az_c }}"
    resource_tags:
      Name: "private-subnet01"
  register: my_private_subnet01

- name: Cria a subnet PRIVADA02
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ private_subnet_2_cidr }}"
    az: "{{ aws_region }}{{ aws_region_az_b }}"
    resource_tags:
      Name: "private-subnet02"
  register: my_private_subnet02

- name: Salva ID da subnets nas variaveis.
  set_fact:
    public_subnet01_id: "{{ my_public_subnet01.subnet.id }}"
    public_subnet02_id: "{{ my_public_subnet02.subnet.id }}"
    private_subnet01_id: "{{ my_private_subnet01.subnet.id }}"
    private_subnet02_id: "{{ my_private_subnet02.subnet.id }}"

- name: Cria gateway para Internet em nosso VPC
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
  register: my_vpc_igw
  
- name: Salva o ID na Variavel igw_id
  set_fact:
      igw_id: "{{ my_vpc_igw.gateway_id }}"

- name: Cria uma rota default na subnets publicas, apontando para o gateway
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: "Public"
    subnets:
      - "{{ public_subnet01_id }}"
      - "{{ public_subnet02_id }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ igw_id }}"